test: |
  go test -cover -coverprofile=coverage.out -v -race
  go tool cover -func=coverage.out

tidy: |
  go mod tidy

# examples
cli_args: |
  go build -o example.exe github.com/roeldev/go-env/examples/cli_args
  ./example.exe -e=foo=bar --e "qux=xoo xoo" -e

os_environ: |
  go build -o example.exe github.com/roeldev/go-env/examples/os_environ
  ./example.exe

read_dotenv: |
  go build -o example.exe github.com/roeldev/go-env/examples/read_dotenv
  ./example.exe
